[/]
animate-app-switch=false
animate-appicon-hover=false
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
animate-window-launch=false
appicon-margin=0
appicon-padding=4
appicon-style='NORMAL'
dot-position='BOTTOM'
dot-style-focused='METRO'
dot-style-unfocused='DASHES'
extension-version=73
group-apps=true
hide-overview-on-startup=false
highlight-appicon-hover=true
hotkeys-overlay-combo='TEMPORARILY'
intellihide=false
overview-click-to-exit=false
panel-anchors='{"DEL-31HQBP3":"MIDDLE","DEL-HSYRX34":"MIDDLE"}'
panel-element-positions='{"DEL-31HQBP3":[{"element":"activitiesButton","visible":true,"position":"stackedTL"},{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"centerMonitor"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}]}'
panel-lengths='{"DEL-31HQBP3":100,"DEL-HSYRX34":100}'
panel-positions='{"DEL-31HQBP3":"TOP","DEL-HSYRX34":"TOP"}'
panel-sizes='{"DEL-31HQBP3":32,"DEL-HSYRX34":32}'
prefs-opened=true
show-apps-icon-file=''
show-favorites=true
show-favorites-all-monitors=true
show-window-previews=false
stockgs-keep-top-panel=false
taskbar-locked=false
trans-use-border=false
window-preview-title-position='TOP'
